### ISSUE TITLE
Add multi-account support for the escrow

### ISSUE THREAD

**Issue by LeCodeurDuDimanche** [iov-one/starnamed#90] opened 2021-07-06 15:52 UTC
Use [ADR 028](https://docs.cosmos.network/master/architecture/adr-028-public-key-addresses.html) to separate the escrow accounts, in order to have one account by escrow.
Currently the escrow module account is used for all escrows.

**Comment by davepuchyr** [comment] 2021-11-18 14:49
Duplicate of https://github.com/iov-one/starnamed/issues/99.

**Closed by davepuchyr** 2021-11-18 14:49 UTC
